"use client";
import Link from "next/link";
import {ArrowRight,BookOpen,Brain,Check,ChevronRight,Clock3,Flame,Pause,Play,Plus,Sparkles,TimerReset} from "lucide-react";
import {useState} from "react";
import {Button} from "@/components/ui/button";
import {Card,CardContent,CardHeader} from "@/components/ui/card";
const tasks=[{course:"AP Physics",title:"Momentum problem set",due:"Tonight",done:false},{course:"English 11",title:"Revise Gatsby thesis",due:"Tomorrow",done:false},{course:"Precalculus",title:"Quiz corrections",due:"Fri",done:true}];
export function Dashboard(){const[dump,setDump]=useState("");const[running,setRunning]=useState(false);const[added,setAdded]=useState(false);const date=new Intl.DateTimeFormat("en-US",{weekday:"long",month:"long",day:"numeric"}).format(new Date());return <div className="space-y-5">
<header className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="mb-1 text-xs font-semibold uppercase tracking-[.18em] text-accent">{date}</p><h1 className="text-2xl font-bold tracking-tight sm:text-3xl">Good evening, Aarush.</h1><p className="mt-1 text-sm text-muted">You have a clean 2h 15m window. Let&apos;s spend it well.</p></div><Button asChild className="hidden sm:inline-flex"><Link href="/planner"><Sparkles size={17}/>Plan my night</Link></Button></header>
<div className="grid gap-5 xl:grid-cols-[minmax(0,1.55fr)_minmax(300px,.75fr)]"><div className="space-y-5">
<Card className="overflow-hidden border-accent/25 bg-[radial-gradient(circle_at_top_right,rgba(98,214,238,.09),transparent_40%),var(--card)]"><CardContent className="p-4 sm:p-6"><div className="mb-3 flex items-center gap-2 text-sm font-semibold"><Brain size={18} className="text-accent"/>Brain dump</div><label htmlFor="quick-dump" className="sr-only">Quickly add what is on your mind</label><textarea id="quick-dump" value={dump} onChange={e=>{setDump(e.target.value);setAdded(false)}} rows={3} placeholder="Physics problems 1–12 by Thursday, study for Friday's calc quiz…" className="min-h-24 w-full resize-none rounded-xl border border-border bg-background/55 p-3 text-sm placeholder:text-muted/70 focus:border-accent"/><div className="mt-3 flex items-center justify-between gap-3"><p className="hidden text-xs text-muted sm:block">Write naturally. You can review everything before it is added.</p><Button onClick={()=>{setAdded(true);setDump("")}} disabled={!dump.trim()} className="ml-auto"><Plus size={16}/>{added?"Added":"Add to planner"}</Button></div></CardContent></Card>
<div className="grid gap-5 md:grid-cols-2"><Card className="border-violet-400/25"><CardHeader><div><p className="text-xs font-semibold uppercase tracking-[.15em] text-violet-300">Next up</p><h2 className="mt-2 text-lg font-semibold">Momentum problem set</h2></div><span className="rounded-lg bg-violet-400/10 px-2 py-1 text-xs text-violet-300">AP Physics</span></CardHeader><CardContent><div className="mb-5 flex items-center gap-4 text-sm text-muted"><span className="flex items-center gap-1.5"><Clock3 size={15}/>7:00–7:45 PM</span><span>45 min</span></div><Button asChild className="w-full"><Link href="/focus"><Play size={16}/>Start focus session</Link></Button></CardContent></Card><Card><CardHeader><div><p className="text-xs font-semibold uppercase tracking-[.15em] text-accent">Study window</p><h2 className="mt-2 text-lg font-semibold">6:45–9:00 PM</h2></div><span className="font-mono text-xs text-muted">2h 15m</span></CardHeader><CardContent><div className="space-y-3 text-sm">{[["bg-violet-400","Physics","45m"],["bg-cyan-400","English","35m"],["bg-amber-300","Precalculus","40m"]].map(x=><div key={x[1]} className="flex items-center gap-3"><span className={`size-2 rounded-full ${x[0]}`}/><span className="flex-1">{x[1]}</span><span className="text-muted">{x[2]}</span></div>)}</div></CardContent></Card></div>
<Card><CardHeader><div><p className="text-xs font-semibold uppercase tracking-[.15em] text-muted">Tonight&apos;s plan</p><h2 className="mt-1 text-lg font-semibold">Three blocks · 2h</h2></div><Link href="/planner" className="flex items-center gap-1 text-xs font-semibold text-accent">Open plan <ChevronRight size={15}/></Link></CardHeader><CardContent className="space-y-2">{[["6:45","Settle in + review","15m","bg-slate-400"],["7:00","Momentum problem set","45m","bg-violet-400"],["7:55","Revise Gatsby thesis","35m","bg-cyan-400"]].map(x=><div key={x[0]} className="grid grid-cols-[44px_4px_1fr_auto] items-center gap-3 rounded-xl border border-transparent p-2 hover:border-border hover:bg-card-strong"><span className="font-mono text-xs text-muted">{x[0]}</span><span className={`h-8 rounded-full ${x[3]}`}/><span className="text-sm font-medium">{x[1]}</span><span className="text-xs text-muted">{x[2]}</span></div>)}</CardContent></Card>
</div><aside className="space-y-5"><Card className="xl:sticky xl:top-21"><CardHeader><div><p className="text-xs font-semibold uppercase tracking-[.15em] text-muted">Quick timer</p><h2 className="mt-1 font-mono text-3xl font-semibold tabular-nums">25:00</h2></div><div className="grid size-10 place-items-center rounded-xl bg-accent/10 text-accent"><TimerReset size={19}/></div></CardHeader><CardContent><div className="mb-4 h-1.5 overflow-hidden rounded-full bg-card-strong"><div className="h-full w-[18%] rounded-full bg-accent shadow-[0_0_10px_rgba(98,214,238,.45)]"/></div><Button onClick={()=>setRunning(v=>!v)} variant={running?"secondary":"default"} className="w-full">{running?<><Pause size={16}/>Pause</>:<><Play size={16}/>Start timer</>}</Button></CardContent></Card>
<Card><CardHeader><div><p className="text-xs font-semibold uppercase tracking-[.15em] text-muted">This week</p><h2 className="mt-1 text-lg font-semibold">Progress</h2></div><Flame className="text-amber-300" size={19}/></CardHeader><CardContent><div className="mb-4 flex items-end gap-2"><span className="text-3xl font-bold">68%</span><span className="pb-1 text-xs text-success">+12% vs last week</span></div><div className="h-2 overflow-hidden rounded-full bg-card-strong"><div className="h-full w-[68%] rounded-full bg-success"/></div><div className="mt-4 grid grid-cols-2 gap-3"><div className="rounded-xl bg-card-strong p-3"><p className="text-xl font-semibold">7.5h</p><p className="text-xs text-muted">focused</p></div><div className="rounded-xl bg-card-strong p-3"><p className="text-xl font-semibold">12</p><p className="text-xs text-muted">completed</p></div></div></CardContent></Card>
<Card><CardHeader><div><p className="text-xs font-semibold uppercase tracking-[.15em] text-muted">Due soon</p><h2 className="mt-1 text-lg font-semibold">Assignments</h2></div><BookOpen size={19} className="text-muted"/></CardHeader><CardContent className="space-y-2">{tasks.map(t=><div key={t.title} className="flex items-center gap-3 rounded-xl py-2"><span className={`grid size-5 place-items-center rounded-full border border-border ${t.done?"border-success bg-success text-[#162007]":""}`}>{t.done&&<Check size={12}/>}</span><div className="min-w-0 flex-1"><p className={`truncate text-sm font-medium ${t.done?"text-muted line-through":""}`}>{t.title}</p><p className="text-xs text-muted">{t.course}</p></div><span className="text-xs text-muted">{t.due}</span></div>)}<Link href="/assignments" className="mt-2 flex min-h-10 items-center justify-center gap-2 rounded-xl text-xs font-semibold text-accent hover:bg-accent/5">View all <ArrowRight size={14}/></Link></CardContent></Card></aside></div></div>}
