"use client";
import Link from "next/link";
import {usePathname} from "next/navigation";
import {BarChart3,BookCheck,CalendarDays,ChevronLeft,Command,Focus,LayoutDashboard,ListTodo,LogOut,Menu,Settings,Sparkles,X} from "lucide-react";
import {useState} from "react";
import {cn} from "@/lib/utils";
const nav=[{href:"/",label:"Overview",icon:LayoutDashboard},{href:"/assignments",label:"Assignments",icon:BookCheck},{href:"/calendar",label:"Calendar",icon:CalendarDays},{href:"/planner",label:"Planner",icon:ListTodo},{href:"/focus",label:"Focus",icon:Focus},{href:"/stats",label:"Stats",icon:BarChart3}];
export function AppShell({children}:{children:React.ReactNode}){const pathname=usePathname();const[collapsed,setCollapsed]=useState(false);const[mobileOpen,setMobileOpen]=useState(false);if(pathname==="/login")return <>{children}</>;
return <div className="min-h-dvh bg-background subtle-grid">
<a href="#main-content" className="fixed left-3 top-3 z-50 -translate-y-24 rounded-lg bg-accent px-3 py-2 text-sm font-semibold text-[#061217] focus:translate-y-0">Skip to content</a>
<aside className={cn("fixed inset-y-0 left-0 z-30 hidden border-r border-border bg-[#0b0e14] transition-[width] duration-200 lg:flex lg:flex-col",collapsed?"w-20":"w-64")}><div className="flex h-18 items-center gap-3 border-b border-border px-5"><div className="grid size-9 shrink-0 place-items-center rounded-xl border border-accent/25 bg-accent/10 text-accent"><Command size={18}/></div>{!collapsed&&<div><p className="text-sm font-bold tracking-[.18em]">SCHOOL HQ</p><p className="text-[11px] text-muted">Fall command center</p></div>}</div><nav aria-label="Primary" className="flex-1 space-y-1 p-3">{nav.map(({href,label,icon:Icon})=>{const active=href==="/"?pathname==="/":pathname.startsWith(href);return <Link key={href} href={href} aria-current={active?"page":undefined} title={collapsed?label:undefined} className={cn("flex min-h-11 items-center gap-3 rounded-xl px-3 text-sm font-medium text-muted transition-colors hover:bg-card-strong hover:text-foreground",active&&"bg-accent/10 text-accent",collapsed&&"justify-center px-0")}><Icon size={18}/>{!collapsed&&label}</Link>})}</nav><div className="space-y-1 border-t border-border p-3"><Link href="/settings" className={cn("flex min-h-11 items-center gap-3 rounded-xl px-3 text-sm text-muted hover:bg-card-strong hover:text-foreground",collapsed&&"justify-center px-0")}><Settings size={18}/>{!collapsed&&"Settings"}</Link><button onClick={()=>setCollapsed(v=>!v)} className="flex min-h-11 w-full items-center justify-center rounded-xl text-muted hover:bg-card-strong hover:text-foreground" aria-label={collapsed?"Expand sidebar":"Collapse sidebar"}><ChevronLeft size={18} className={cn("transition-transform",collapsed&&"rotate-180")}/></button></div></aside>
{mobileOpen&&<div className="fixed inset-0 z-40 bg-black/65 backdrop-blur-sm lg:hidden" onClick={()=>setMobileOpen(false)}/>}<aside className={cn("fixed inset-y-0 left-0 z-50 w-[min(86vw,340px)] border-r border-border bg-[#0b0e14] p-4 transition-transform lg:hidden",mobileOpen?"translate-x-0":"-translate-x-full")} aria-hidden={!mobileOpen}><div className="mb-5 flex items-center justify-between"><span className="font-bold tracking-[.16em]">SCHOOL HQ</span><button onClick={()=>setMobileOpen(false)} className="grid size-11 place-items-center rounded-xl text-muted" aria-label="Close menu"><X/></button></div><nav className="space-y-1">{nav.map(({href,label,icon:Icon})=><Link key={href} href={href} className={cn("flex min-h-12 items-center gap-3 rounded-xl px-3 text-muted",pathname===href&&"bg-accent/10 text-accent")}><Icon size={19}/>{label}</Link>)}</nav><div className="mt-4 border-t border-border pt-4"><Link href="/settings" className="flex min-h-12 items-center gap-3 rounded-xl px-3 text-muted"><Settings size={19}/>Settings</Link><Link href="/login" className="flex min-h-12 items-center gap-3 rounded-xl px-3 text-muted"><LogOut size={19}/>Sign out</Link></div></aside>
<div className={cn("transition-[padding] duration-200",collapsed?"lg:pl-20":"lg:pl-64")}><header className="sticky top-0 z-20 flex h-16 items-center justify-between border-b border-border bg-background/90 px-4 backdrop-blur-xl sm:px-6 lg:px-8"><button onClick={()=>setMobileOpen(true)} className="grid size-11 place-items-center rounded-xl text-muted lg:hidden" aria-label="Open menu"><Menu size={20}/></button><div className="hidden items-center gap-2 text-xs text-muted sm:flex"><span className="size-2 rounded-full bg-success shadow-[0_0_12px_rgba(163,230,53,.7)]"/>Everything synced</div><Link href="/planner" className="ml-auto inline-flex min-h-10 items-center gap-2 rounded-xl bg-accent/10 px-3 text-xs font-semibold text-accent hover:bg-accent/15"><Sparkles size={15}/>Plan my night</Link></header><main id="main-content" className="mx-auto min-h-[calc(100dvh-4rem)] w-full max-w-[1500px] px-4 pb-28 pt-5 sm:px-6 sm:pt-7 lg:px-8 lg:pb-8">{children}</main></div>
<nav aria-label="Mobile primary" className="fixed inset-x-0 bottom-0 z-30 grid grid-cols-5 border-t border-border bg-[#0b0e14]/96 px-1 pb-[max(.45rem,env(safe-area-inset-bottom))] pt-1 backdrop-blur-xl lg:hidden">{[nav[0],nav[1],nav[3],nav[4],{href:"#menu",label:"More",icon:Menu}].map(({href,label,icon:Icon})=>{const active=href!=="#menu"&&(href==="/"?pathname==="/":pathname.startsWith(href));return href==="#menu"?<button key={href} onClick={()=>setMobileOpen(true)} className="flex min-h-14 flex-col items-center justify-center gap-1 text-[10px] text-muted"><Icon size={19}/>{label}</button>:<Link key={href} href={href} aria-current={active?"page":undefined} className={cn("flex min-h-14 flex-col items-center justify-center gap-1 text-[10px] text-muted",active&&"text-accent")}><Icon size={19}/>{label}</Link>})}</nav>
</div>}
