"use client";
import {CalendarDays,ChevronLeft,ChevronRight,Download,FileUp,LoaderCircle,X} from "lucide-react";
import {useRef,useState} from "react";
import {Button} from "@/components/ui/button";
import {Card,CardContent} from "@/components/ui/card";
import {PageHeader} from "@/components/page-header";
import {calendarEvents} from "@/lib/mock-data";
import type {CalendarEvent} from "@/types/api";
const days=["Mon 24","Tue 25","Wed 26","Thu 27","Fri 28","Sat 29","Sun 30"];
const style:Record<CalendarEvent["kind"],string>={class:"border-violet-400/40 bg-violet-400/15 text-violet-200",busy:"border-rose-400/40 bg-rose-400/12 text-rose-200",study_window:"border-dashed border-cyan-400/40 bg-cyan-400/5 text-cyan-200",study_block:"border-cyan-400/45 bg-cyan-400/15 text-cyan-100",completed:"border-lime-400/40 bg-lime-400/10 text-lime-200",ignored:"border-border bg-card-strong text-muted"};
export function CalendarView(){const[selected,setSelected]=useState(4);const[imported,setImported]=useState<CalendarEvent[]>([]);const[importing,setImporting]=useState(false);const input=useRef<HTMLInputElement>(null);async function importFile(file?:File){if(!file)return;setImporting(true);await new Promise(r=>setTimeout(r,650));setImported([{id:"i1",title:"Student Council",startsAt:"2026-08-31T15:30:00-05:00",endsAt:"2026-08-31T16:30:00-05:00",kind:"busy"},{id:"i2",title:"Library",startsAt:"2026-09-01T17:00:00-05:00",endsAt:"2026-09-01T18:30:00-05:00",kind:"study_window"}]);setImporting(false)}return <div className="space-y-5"><PageHeader eyebrow="Calendar" title="Your week at a glance." description="Classes, commitments, and study time without the seven-column phone squish." action={<><input ref={input} type="file" accept=".ics,text/calendar" className="sr-only" onChange={e=>importFile(e.target.files?.[0])}/><Button variant="secondary" onClick={()=>input.current?.click()}>{importing?<LoaderCircle className="animate-spin" size={16}/>:<FileUp size={16}/>}Import .ics</Button></>}/>
<div className="flex items-center justify-between"><div className="flex items-center gap-2"><Button variant="secondary" size="icon" aria-label="Previous week"><ChevronLeft size={17}/></Button><Button variant="secondary" size="icon" aria-label="Next week"><ChevronRight size={17}/></Button><span className="ml-2 text-sm font-semibold">August 24–30, 2026</span></div><Button variant="ghost" size="sm"><CalendarDays size={15}/>Today</Button></div>
<div className="flex gap-2 overflow-x-auto pb-1 md:hidden scrollbar-none" aria-label="Choose day">{days.map((d,i)=><button key={d} onClick={()=>setSelected(i)} className={`min-h-11 shrink-0 rounded-xl px-4 text-xs font-semibold ${selected===i?"bg-accent text-[#061217]":"border border-border bg-card text-muted"}`}>{d}</button>)}</div>
<Card className="md:hidden"><CardContent className="space-y-3"><p className="text-xs uppercase tracking-[.15em] text-muted">Agenda · {days[selected]}</p>{calendarEvents.filter(e=>new Date(e.startsAt).getDay()===(selected+1)%7).length?calendarEvents.filter(e=>new Date(e.startsAt).getDay()===(selected+1)%7).map(e=><Event key={e.id} event={e}/>):<div className="py-14 text-center"><p className="font-medium">Wide open.</p><p className="mt-1 text-sm text-muted">No events on this day.</p></div>}</CardContent></Card>
<Card className="hidden overflow-hidden md:block"><div className="grid grid-cols-[56px_repeat(7,minmax(90px,1fr))] border-b border-border bg-card-strong"><div/><>{days.map(d=><div key={d} className="border-l border-border p-3 text-center text-xs font-semibold">{d}</div>)}</></div><div className="grid grid-cols-[56px_repeat(7,minmax(90px,1fr))]"><div>{[8,10,12,14,16,18,20].map(h=><div key={h} className="h-24 border-b border-border pr-2 pt-1 text-right font-mono text-[10px] text-muted">{h>12?h-12:h} {h>=12?"PM":"AM"}</div>)}</div>{days.map((_,day)=><div key={day} className="relative h-[672px] border-l border-border bg-[linear-gradient(var(--border)_1px,transparent_1px)] bg-[length:100%_96px]">{calendarEvents.filter(e=>new Date(e.startsAt).getDay()===(day+1)%7).map(e=>{const s=new Date(e.startsAt),end=new Date(e.endsAt);const top=(s.getHours()+s.getMinutes()/60-8)*48;const height=Math.max(28,(end.getTime()-s.getTime())/3600000*48);return <div key={e.id} className={`absolute inset-x-1 overflow-hidden rounded-lg border p-1.5 text-[10px] leading-tight ${style[e.kind]}`} style={{top,height}}><strong className="block truncate">{e.title}</strong><span className="opacity-75">{s.toLocaleTimeString([],{hour:"numeric",minute:"2-digit"})}</span></div>})}</div>)}</div></Card>
<div className="flex flex-wrap gap-3 text-xs text-muted">{[["bg-violet-400","Class"],["bg-rose-400","Busy"],["bg-cyan-400","Study"],["bg-lime-400","Completed"]].map(x=><span className="flex items-center gap-1.5" key={x[1]}><span className={`size-2 rounded-full ${x[0]}`}/>{x[1]}</span>)}</div>
{imported.length>0&&<div className="fixed inset-0 z-50 grid place-items-end bg-black/70 p-0 sm:place-items-center sm:p-6"><section role="dialog" aria-modal="true" aria-labelledby="classify-title" className="max-h-[90dvh] w-full overflow-y-auto rounded-t-3xl border border-border bg-card p-5 sm:max-w-xl sm:rounded-2xl"><div className="flex items-start justify-between"><div><p className="text-xs uppercase tracking-[.15em] text-accent">Import complete</p><h2 id="classify-title" className="mt-1 text-xl font-semibold">Classify calendar events</h2><p className="mt-1 text-sm text-muted">Tell School HQ what it can schedule around.</p></div><Button variant="ghost" size="icon" aria-label="Close classification" onClick={()=>setImported([])}><X size={18}/></Button></div><div className="my-5 space-y-3">{imported.map((e,i)=><div key={e.id} className="rounded-xl border border-border p-3"><p className="text-sm font-semibold">{e.title}</p><p className="mt-1 text-xs text-muted">{new Date(e.startsAt).toLocaleString([],{weekday:"short",hour:"numeric",minute:"2-digit"})}</p><div className="mt-3 grid grid-cols-3 gap-2">{(["busy","study_window","ignored"] as const).map(k=><button key={k} onClick={()=>setImported(xs=>xs.map((x,j)=>j===i?{...x,kind:k}:x))} className={`min-h-10 rounded-lg border px-2 text-xs font-semibold ${e.kind===k?style[k]:"border-border text-muted"}`}>{k==="study_window"?"Study":k[0].toUpperCase()+k.slice(1)}</button>)}</div></div>)}</div><Button className="w-full" onClick={()=>setImported([])}><Download size={16}/>Save classifications</Button></section></div>}</div>}
function Event({event}:{event:CalendarEvent}){const s=new Date(event.startsAt),e=new Date(event.endsAt);return <div className={`rounded-xl border p-3 ${style[event.kind]}`}><div className="flex items-start justify-between gap-3"><p className="text-sm font-semibold">{event.title}</p><span className="text-xs capitalize opacity-75">{event.kind.replace("_"," ")}</span></div><p className="mt-2 font-mono text-xs opacity-75">{s.toLocaleTimeString([],{hour:"numeric",minute:"2-digit"})}–{e.toLocaleTimeString([],{hour:"numeric",minute:"2-digit"})}</p></div>}
