"use client";
import {AlertTriangle,Check,ChevronLeft,Clock3,GripVertical,LoaderCircle,Plus,RefreshCw,Sparkles,Trash2} from "lucide-react";
import {useState} from "react";
import {Button} from "@/components/ui/button";
import {Card,CardContent,CardHeader} from "@/components/ui/card";
import {PageHeader} from "@/components/page-header";
import {api} from "@/lib/api-client";
import {courses,plan as mockPlan} from "@/lib/mock-data";
import type {AssignmentDraft,StudyPlan} from "@/types/api";
type Stage="dump"|"review"|"timeline";
const seed="Physics momentum problems 1–12 are due tomorrow. Study for the calculus quiz Friday morning. I also need to revise my Gatsby thesis, probably 35 minutes.";
export function Planner(){const[stage,setStage]=useState<Stage>("dump");const[text,setText]=useState(seed);const[drafts,setDrafts]=useState<AssignmentDraft[]>([]);const[loading,setLoading]=useState(false);const[error,setError]=useState("");const[plan,setPlan]=useState<StudyPlan>(mockPlan);
async function parse(){setLoading(true);setError("");try{const result=await api.parseBrainDump({text,timezone:Intl.DateTimeFormat().resolvedOptions().timeZone});setDrafts(result.assignments);setStage("review")}catch(e){setError(e instanceof Error?e.message:"Could not parse that brain dump.")}finally{setLoading(false)}}
async function generate(){setLoading(true);try{setPlan(await api.generatePlan());setStage("timeline")}catch(e){setError(e instanceof Error?e.message:"Plan generation failed.")}finally{setLoading(false)}}
function update(index:number,patch:Partial<AssignmentDraft>){setDrafts(ds=>ds.map((d,i)=>i===index?{...d,...patch}:d))}
return <div className="space-y-5"><PageHeader eyebrow="Night planner" title={stage==="dump"?"Clear your head.":stage==="review"?"Review the details.":"Your night, mapped."} description={stage==="dump"?"Drop everything here. School HQ will structure it, then you stay in control.":stage==="review"?"Yellow fields need a human glance. The robot is useful, not clairvoyant.":"A realistic plan with room to breathe, not a productivity hostage situation."}/>
<div className="flex items-center gap-2" aria-label="Planner progress">{["Brain dump","Review","Timeline"].map((label,i)=>{const current=["dump","review","timeline"].indexOf(stage);return <div key={label} className="flex flex-1 items-center gap-2"><span className={`grid size-6 shrink-0 place-items-center rounded-full text-xs font-bold ${i<=current?"bg-accent text-[#061217]":"bg-card-strong text-muted"}`}>{i<current?<Check size={13}/>:i+1}</span><span className={`hidden text-xs sm:inline ${i<=current?"text-foreground":"text-muted"}`}>{label}</span>{i<2&&<span className={`h-px flex-1 ${i<current?"bg-accent":"bg-border"}`}/>}</div>})}</div>
{error&&<div role="alert" className="flex items-center gap-2 rounded-xl border border-danger/30 bg-danger/10 p-3 text-sm text-danger"><AlertTriangle size={17}/>{error}</div>}
{stage==="dump"&&<Card className="border-accent/20"><CardContent className="p-4 sm:p-6"><label htmlFor="brain-dump" className="mb-3 block text-sm font-semibold">What&apos;s on your plate?</label><textarea id="brain-dump" value={text} onChange={e=>setText(e.target.value)} className="min-h-64 w-full resize-y rounded-xl border border-border bg-background/60 p-4 text-base leading-7 placeholder:text-muted focus:border-accent" placeholder="Type assignments, due dates, worries, rough estimates…"/><div className="mt-4 flex flex-col-reverse gap-3 sm:flex-row sm:items-center sm:justify-between"><p className="text-xs text-muted">Nothing is saved until you confirm the review.</p><Button onClick={parse} disabled={loading||!text.trim()}>{loading?<LoaderCircle className="animate-spin" size={17}/>:<Sparkles size={17}/>}Parse brain dump</Button></div></CardContent></Card>}
{stage==="review"&&<div className="space-y-4"><div className="space-y-3">{drafts.map((d,i)=><Card key={`${d.title}-${i}`}><CardContent className="grid gap-4 p-4 md:grid-cols-[1.4fr_1fr_1fr_110px_44px] md:items-end"><Field label="Assignment" warning={(d.confidence?.title??1)<.75}><input value={d.title} onChange={e=>update(i,{title:e.target.value})} className="input"/></Field><Field label="Course" warning={(d.confidence?.courseId??1)<.75}><select value={d.courseId} onChange={e=>update(i,{courseId:e.target.value})} className="input">{courses.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></Field><Field label="Due" warning={(d.confidence?.dueAt??1)<.75}><input type="datetime-local" value={d.dueAt?.slice(0,16)??""} onChange={e=>update(i,{dueAt:e.target.value||null})} className="input"/></Field><Field label="Minutes" warning={(d.confidence?.estimatedMinutes??1)<.75}><input type="number" min="5" step="5" value={d.estimatedMinutes??""} onChange={e=>update(i,{estimatedMinutes:Number(e.target.value)||null})} className="input"/></Field><Button variant="ghost" size="icon" aria-label={`Delete ${d.title}`} onClick={()=>setDrafts(ds=>ds.filter((_,j)=>j!==i))}><Trash2 size={17}/></Button></CardContent></Card>)}</div><Button variant="secondary" onClick={()=>setDrafts(ds=>[...ds,{title:"New assignment",courseId:"physics",dueAt:null,estimatedMinutes:30,priority:"medium"}])}><Plus size={16}/>Add task</Button><div className="flex flex-col-reverse gap-3 border-t border-border pt-5 sm:flex-row sm:justify-between"><Button variant="ghost" onClick={()=>setStage("dump")}><ChevronLeft size={16}/>Back</Button><Button onClick={generate} disabled={loading||!drafts.length}>{loading?<LoaderCircle className="animate-spin" size={17}/>:<Sparkles size={17}/>}Confirm and generate plan</Button></div></div>}
{stage==="timeline"&&<div className="grid gap-5 xl:grid-cols-[1fr_320px]"><Card><CardHeader><div><p className="text-xs uppercase tracking-[.15em] text-muted">Friday evening</p><h2 className="mt-1 text-lg font-semibold">6:45–9:00 PM</h2></div><Button variant="secondary" size="sm" onClick={generate}><RefreshCw size={14}/>Regenerate</Button></CardHeader><CardContent className="space-y-3">{plan.blocks.map((b,i)=><div key={b.id} className="group grid grid-cols-[22px_58px_5px_1fr_auto] items-center gap-3 rounded-xl border border-border bg-card-strong p-3"><GripVertical size={17} className="cursor-grab text-muted"/><span className="font-mono text-xs text-muted">{new Date(b.startsAt).toLocaleTimeString([],{hour:"numeric",minute:"2-digit"})}</span><span className={`h-11 rounded-full ${b.courseId==="physics"?"bg-violet-400":b.courseId==="english"?"bg-cyan-400":b.courseId==="precalc"?"bg-amber-300":"bg-slate-500"}`}/><div><input aria-label={`Edit ${b.title}`} value={b.title} onChange={e=>setPlan(p=>({...p,blocks:p.blocks.map((x,j)=>j===i?{...x,title:e.target.value}:x)}))} className="w-full bg-transparent text-sm font-semibold focus:text-accent"/><p className="mt-1 flex items-center gap-1 text-xs text-muted"><Clock3 size={12}/>{Math.round((new Date(b.endsAt).getTime()-new Date(b.startsAt).getTime())/60000)} minutes</p></div><Button variant="ghost" size="icon" aria-label={`Remove ${b.title}`} onClick={()=>setPlan(p=>({...p,blocks:p.blocks.filter(x=>x.id!==b.id)}))}><Trash2 size={16}/></Button></div>)}</CardContent></Card><aside className="space-y-4"><Card><CardContent><p className="text-xs uppercase tracking-[.15em] text-muted">Plan health</p><p className="mt-3 text-3xl font-bold">2h 15m</p><p className="mt-1 text-sm text-muted">20 minutes of buffer built in.</p><div className="mt-4 h-2 rounded-full bg-card-strong"><div className="h-full w-[85%] rounded-full bg-success"/></div></CardContent></Card><Button className="w-full" onClick={()=>setError("")}><Check size={17}/>Use this plan</Button><Button variant="ghost" className="w-full" onClick={()=>setStage("review")}><ChevronLeft size={16}/>Edit assignments</Button></aside></div>}</div>}
function Field({label,warning,children}:{label:string;warning?:boolean;children:React.ReactNode}){return <label className="block"><span className={`mb-1.5 flex items-center gap-1 text-xs font-semibold ${warning?"text-amber-300":"text-muted"}`}>{warning&&<AlertTriangle size={12}/>} {label}</span>{children}</label>}
